name: Tempo
description: A time-tracking app for teams
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # QR Scanning
  qrscan: ^0.2.17
  # SQLite
  sqflite: ^1.3.0+2
  # HTTP requests
  dio: ">=3.0.9 <6.0.0"
  # A type conversion dio client generator using source_gen inspired by Retrofit
  retrofit: ">=1.3.4 <5.0.0"
  # Defines the annotations used by json_serializable
  json_annotation: ">=3.0.1 <5.0.0"
  # Geolocation
  location: ">=3.0.2 <5.0.0"
  # Google Maps for Flutter (newer versions introduce breaking changes)
  google_maps_flutter: 0.5.25
  # SVG icons
  flutter_svg: ">=0.17.4 <3.0.0"
  # DateFormat
  intl: ">=0.16.1 <0.19.0"
  # A mixture between dependency injection (DI) and state management
  provider: ^4.1.2
  # Firebase Authentication
  firebase_auth: ">=0.16.0 <5.0.0"
  # Google Fonts
  google_fonts: ">=1.1.0 <5.0.0"
  # Directional slide actions that can be dismissed
  flutter_slidable: ^0.5.4
  # Generate random Strings
  random_string: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Generate files using Dart code
  build_runner: ">=1.10.0 <3.0.0"
  # Dart Build System builders for handling JSON
  json_serializable: ">=3.3.0 <7.0.0"
  # Codegen for Retrofit
  retrofit_generator: ">=1.3.7 <7.0.0"

flutter:
  uses-material-design: true
  assets:
    - images/