name: Tempo
description: A time-tracking app for teams
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # QR Scanning
  qrscan: ^0.2.17
  # SQLite
  sqflite: ^1.2.0
  # HTTP requests
  http: ^0.12.0+4
  # Geolocation
  location: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/